apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/k3s/pv/ollama-models"
