---
apiVersion: batch/v1
kind: Job
metadata:
  name: pull-gemma3-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pull-model
          image: ollama/ollama:latest
          command:
            - /bin/sh
            - -c
            - |
              ollama serve &  # Start the server in the background
              sleep 10
              ollama pull gemma3:1b-it-q4_K_M
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          emptyDir: {}
