---
apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-qa
spec:
  template:
    spec:
      containers:
        - name: tester
          image: ollama/ollama:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt-get update && apt-get install -y jq curl
              MODELS=(
                phi
                gemma3:4b-it-q4_K_M
                mistral
                mistral:7b-instruct-v0.3-q5_0
                openhermes
              )
              for model in "${MODELS[@]}"; do
                OLLAMA_HOST=http://ollama:11434 ollama pull "$model"
              done
              for model in "${MODELS[@]}"; do
                echo "Testing $model..."
                start=$(date +%s%3N)
                curl -s -X POST http://ollama:11434/api/generate \
                  -d "{\"model\": \"$model\", \"prompt\": \"Write a haiku about satellites.\"}" \
                  | jq .
                end=$(date +%s%3N)
                echo "Duration: $((end - start)) ms"
                echo ""
              done
          env:
            - name: OLLAMA_HOST
              value: "http://ollama:11434"
      restartPolicy: Never
  backoffLimit: 1
