---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bridge
  template:
    metadata:
      labels:
        app: discord-bridge
    spec:
      containers:
        - name: discord-bridge
          image: discord-bridge:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN
            - name: REPLICATE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: replicate-token
                  key: REPLICATE_API_TOKEN
            - name: OLLAMA_URL
              value: http://ollama:11434
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
